import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;

const api='http://10.0.2.2:5000/api';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(colorSchemeSeed:Colors.blue,useMaterial3:true),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{List items=[];bool loading=true;@override void initState(){super.initState();fetch();}Future<void> fetch()async{final r=await http.get(Uri.parse('$api/products'));if(r.statusCode==200)setState((){items=jsonDecode(r.body);loading=false;});}Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('⚡ Smart Electronics'),actions:[IconButton(onPressed:fetch,icon:const Icon(Icons.refresh))]),body:loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:fetch,child:GridView.builder(padding:const EdgeInsets.all(12),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:2,childAspectRatio:.68,crossAxisSpacing:12,mainAxisSpacing:12),itemCount:items.length,itemBuilder:(c,i){final p=items[i];return Card(clipBehavior:Clip.antiAlias,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Image.network(p['image_url'],height:130,width:double.infinity,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const SizedBox(height:130,child:Icon(Icons.image))),Padding(padding:const EdgeInsets.all(10),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p['name'],maxLines:2,style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:8),Text('₹${p['price']}',style:const TextStyle(color:Colors.blue,fontWeight:FontWeight.bold)),Text(p['brand']),const SizedBox(height:6),SizedBox(width:double.infinity,child:ElevatedButton(onPressed:(){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Login to add products to cart')));},child:const Text('View')))]));}));}}
